#Debug mode outputs specific information to the console
#DEFAULT-debugmode=false

#LBRYcrd URL is required for chainquery to query the blockchain
#DEFAULT-lbrycrdurl="rpc://lbry:lbry@localhost:9245"

#MySQL DSN is required for chainquery to store information.
#DEFAULT-mysqldsn="lbry:lbry@tcp(localhost:3305)/lbrycrd"

#Profile mode enables and disables the reporting of a profile for chainquery
#DEFAULT-profilemode=false

#Daemon mode tells chainquery how hard it should work catch up processing the blockchain
#DEFAULT-deamonmode=0 #BeastMode it continuously process block after block until caughtup.
#daemonmode=1 #SlowAndSteadyMode it will process block with a frequency of 1 block every 100ms
#daemonmode=2 #DelayMode it will process a block with a configured delay frequency (set via 'processingdelay')
#daemonmode=3 #DaemonMode it will process a block every iteration of the daemon.

#Default client timeout is for communication with the api of chainquery
#DEFAULT-defaultclienttimeout=20 #Measured in seconds

#Processing delay is used to determine how frequently chainquery should process a block
# It is only used if Daemon mode is set to delay mode
#DEFAULT-processingdelay=100 #Measured in milliseconds

#Daemon delay is the frequency at which chainquery checks for work to do.
#DEFAULT-daemondelay=1 #Measured in seconds
