# this file is used for generating the models, not for connecting to the db
# so username/password are the local dev login, not the production login

pkgname="model"
output="model"
[mysql]
  blacklist=["gorp_migrations"]
  dbname="chainquery"
  host="localhost"
  port=3306
  user="lbry"
  pass="lbry"
  sslmode="false"